### ISSUE TITLE
v1.0.1 Elasticsearch __init__() throws error related to `user`

### ISSUE THREAD

**Issue by jornh** [lyft/amundsensearchlibrary#24]
After merge of #17 I took master for a test drive 

It does not work for me when configured to use the ES (and Neo4j backend)

Looks like the named parameters signature here:

https://github.com/lyft/amundsensearchlibrary/blob/1a05eb2f063a0805d16261fcf4a6751023f502f9/search_service/proxy/elasticsearch.py#L33-L34

... should match `user` and `password` in the `__init__.py` file. 

I made the modification to Elasticsearch.py - and was able to make it work locally. Would like confirmation of if others see this as well.

Other than that I’m super excited about that #17 got merged for two reasons:

* Atlas with search (which I didn’t try yet) 
* That proxy is now configurable through env vars, with naming similar to that for metadata service, so config.py changes isn’t needed any more! 👍 @Whazor

**Comment by feng-tao** [comment]
@jornh good catch. Would you mind creating a fix and bump the version? Thanks.

**Comment by jornh** [comment]
@feng-tao I can certainly take a shot at it. What I just did locally for now was just renaming the parameters in the two lines. But circling back what worries me more is that there are more lines with that naming, and none of it broke any unit tests. 

So what do you suggest? Quickly just add the changes, so master/PyPi isn't - just as - broken then figuring out how to add tests for this in a followup PR.

**Comment by feng-tao** [comment]
@jornh , yeah, actually let me take a look first and see if anything else besides the user/password rename is missing.

**Comment by jornh** [comment]
👍 appreciated! Will go to bed now 1 AM here.

**Comment by Whazor** [comment]
Sorry for breaking elastic search! Made a pull request that should fix it and add tests
