### ISSUE TITLE
Automate Docker push driven by CI

### ISSUE THREAD

**Issue by jornh** [lyft/amundsensearchlibrary#25]
Would be super-nice to have Travis driven docker updates similar to what got added to frontend:

https://github.com/lyft/amundsenfrontendlibrary/blob/master/.travis.yml#L42-L48

@jinhyukchang seems like low-hanging fruit?

(While at it same goes for metadata service)

**Comment by feng-tao** [comment]
@jinhyukchang just commit the docker change :)
