### ISSUE TITLE
Endpoints for document actions

### ISSUE THREAD

**Issue by alran** [lyft/amundsensearchlibrary#38]
At Square we have a DocumentAPI for adding/updating/deleting documents in our elasticsearch index. Would anyone be interested in having this in the amundsensearchlibrary? I would be happy to upstream our changes!

**Comment by alran** [comment]
update: I'm working on making a PR for this

**Comment by alran** [comment]
definitely - I have gotten distracted with a few things but I will have something to show you either tomorrow or early next week

**Comment by alran** [comment]
@feng-tao pls see https://github.com/lyft/amundsensearchlibrary/pull/40

**Comment by jornh** [comment]
With #40 just merged it seems this issue can be closed, right?

**Comment by feng-tao** [comment]
+1
